name: flutter_simawi_app
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  age_calculator: ^1.0.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10
  go_router: ^13.2.1
  intl: ^0.17.0
  path_provider: ^2.0.11
  sqflite: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Thin.ttf
        - asset: fonts/Lexend-ExtraLight.ttf
        - asset: fonts/Lexend-Light.ttf
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-Medium.ttf
        - asset: fonts/Lexend-SemiBold.ttf
        - asset: fonts/Lexend-Bold.ttf
        - asset: fonts/Lexend-ExtraBold.ttf
        - asset: fonts/Lexend-Black.ttf

  assets:
    - assets/profile/
